on: 
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

name: Notify about PR ready for review

jobs:
  slackNotification:
    name: Slack Notification
    if: startsWith(github.head_ref, 'dependabot/') # This step only runs when PR is created by Dependabot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: kv109/action-ready-for-review@0.1
      env:
        SLACK_CHANNEL: your-slack-channel           # required
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }} # required
