name: 'Dependabot PR alert to Slack'

on:
  pull_request:
    branches: [ "main" ] # Specifies the target branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Notify-PR:
    runs-on: ubuntu-latest
    # Latest version available at: https://github.com/jun3453/slack-pr-open-notification-action/releases
    steps:
      - name: Slack notification
        if: startsWith(github.head_ref, 'dependabot/') # This step only runs when PR is created by Dependabot
        uses: jun3453/slack-pr-open-notification-action@v1.3.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # This secret need to be created
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
          PULL_REQUEST_AUTHOR_NAME: 'dependabot'
          PULL_REQUEST_AUTHOR_ICON_URL: 'dependabot'
          PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
          PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
          PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
          PULL_REQUEST_COMPARE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
          PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
          PULL_REQUEST_BASE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}
          IS_SEND_HERE_MENTION: true
          MAKE_PRETTY: false
          MAKE_COMPACT: false
          IS_PR_FROM_FORK: false
